# This is the config of the spell checker GitHub Action (i.e., https://github.com/marketplace/actions/check-spelling).

on:
  push:
  pull_request_target:
name: Spell Checker
jobs:
  spellChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Check spelling
        uses: check-spelling/check-spelling@0.0.16-alpha
        with:
          bucket: .github/actions
          project: spelling
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: 1
          